# Generated by Django 2.2.12 on 2021-08-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
