# Generated by Django 2.2.12 on 2021-08-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherArrangment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Course')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Section')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Teacher')),
            ],
        ),
    ]
