# Generated by Django 2.2.12 on 2021-08-09 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210808_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Section'),
        ),
        migrations.AlterField(
            model_name='teacherarrangment',
            name='section',
            field=models.ManyToManyField(to='student.Section'),
        ),
    ]
