# Generated by Django 2.2.12 on 2021-09-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210809_0711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assesment',
            unique_together={('course', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherarrangment',
            unique_together={('course', 'teacher')},
        ),
    ]
