# Generated by Django 2.2.12 on 2021-09-09 09:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210908_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='asgt',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
