# Generated by Django 3.2.7 on 2021-09-10 19:16

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_assesment_asgt'),
    ]

    operations = [
        migrations.CreateModel(
            name='jsoncheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=67, null=True)),
                ('exam', jsonfield.fields.JSONField(null=True)),
                ('total', models.FloatField(null=True)),
            ],
        ),
    ]
