# Generated by Django 3.2.7 on 2021-09-10 20:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_jsoncheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncheck',
            name='exam',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
    ]
