# Generated by Django 3.2.7 on 2021-09-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_jsoncheck_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='propic',
            field=models.ImageField(default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
