# Generated by Django 3.2.7 on 2021-09-12 11:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_assesment_asgt'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='assined_section',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
