# Generated by Django 3.2.7 on 2021-09-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_section_assined_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.teacher'),
        ),
    ]
