# Generated by Django 3.2.7 on 2021-09-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_assesment_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='assined_section',
        ),
    ]
