# Generated by Django 3.2.7 on 2021-09-12 14:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_section_assined_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='withcourse',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
