# Generated by Django 3.2.7 on 2021-09-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_section_withcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
