# Generated by Django 3.2.7 on 2021-09-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20210914_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('yellow', 'yelloe')], max_length=200, null=True),
        ),
    ]
