# Generated by Django 3.2.7 on 2021-09-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20210914_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='standing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
