# Generated by Django 2.2.12 on 2021-09-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_assesment_standing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='result',
            field=models.FloatField(default=0),
        ),
    ]
