# Generated by Django 2.2.12 on 2021-09-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20210915_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='result',
            field=models.FloatField(null=True),
        ),
    ]
