# Generated by Django 2.2.12 on 2021-09-15 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20210915_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='result',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Teacher'),
        ),
    ]
