# Generated by Django 2.2.12 on 2021-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20210915_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherarrangment',
            name='section',
            field=models.ManyToManyField(blank=True, to='student.Section'),
        ),
    ]
