# Generated by Django 2.2.12 on 2021-09-16 11:26

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_auto_20210915_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semister', models.CharField(choices=[('semisterI', 'semisterI'), ('semisterII', 'semisterII')], default='semisterI', max_length=200, unique=True)),
                ('active', models.BooleanField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='position',
            field=jsonfield.fields.JSONField(default={'grade9': {'pass': True, 'total': 0}}),
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('standing', models.IntegerField(blank=True, null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Grade')),
                ('semister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Semister')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
