# Generated by Django 2.2.12 on 2021-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20210916_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='result',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('student', 'semister')},
        ),
    ]
