# Generated by Django 2.2.12 on 2021-09-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_auto_20210916_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Section'),
        ),
    ]
