# Generated by Django 2.2.12 on 2021-09-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_transcript_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='standing',
            new_name='standing_all',
        ),
        migrations.AddField(
            model_name='transcript',
            name='standing_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
