# Generated by Django 2.2.12 on 2021-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_auto_20210916_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assesment',
            old_name='standing',
            new_name='standing_al',
        ),
        migrations.AddField(
            model_name='assesment',
            name='standing_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('student', 'semister', 'grade')},
        ),
    ]
