# Generated by Django 2.2.12 on 2021-09-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_auto_20210916_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assesment',
            old_name='standing_al',
            new_name='standing_all',
        ),
    ]
