# Generated by Django 3.2.7 on 2021-09-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_transcript_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherarrangment',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
