# Generated by Django 2.2.12 on 2021-09-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_teacherarrangment_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semister',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='semister',
            name='semister',
            field=models.CharField(choices=[('semisterI', 'semisterI'), ('semisterII', 'semisterII')], default='semisterI', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='semister',
            unique_together={('semister', 'active')},
        ),
    ]
