# Generated by Django 2.2.12 on 2021-09-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20210918_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcript',
            options={'ordering': ['student']},
        ),
        migrations.AddField(
            model_name='transcript',
            name='wholeavg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='wholestanding_all',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='wholetotal',
            field=models.FloatField(null=True),
        ),
    ]
