# Generated by Django 2.2.12 on 2021-09-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_auto_20210918_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
