# Generated by Django 2.2.12 on 2021-09-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_transcript_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enroll_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='section',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='semister',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assesment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
