# Generated by Django 2.2.12 on 2021-09-19 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0042_auto_20210919_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('ministry_result', models.FloatField(max_length=200, null=True)),
                ('matric_result', models.FloatField(blank=True, max_length=200, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_phone_number', models.CharField(max_length=200, null=True)),
                ('position', jsonfield.fields.JSONField(default={'grade9': {'pass': True, 'total': 0}})),
                ('propic', models.ImageField(default='profile1.jpg', null=True, upload_to='')),
                ('enroll_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Grade')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
                ('avg', models.FloatField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('wholeavg', models.FloatField(null=True)),
                ('wholetotal', models.FloatField(null=True)),
                ('wholestanding_all', models.IntegerField(blank=True, null=True)),
                ('standing_all', models.IntegerField(blank=True, null=True)),
                ('standing_sec', models.IntegerField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Grade')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Section')),
                ('semister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Semister')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'ordering': ['student'],
                'unique_together': {('student', 'semister', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asgt', jsonfield.fields.JSONField(default={})),
                ('mid', models.FloatField(null=True)),
                ('final', models.FloatField(null=True)),
                ('result', models.FloatField(null=True)),
                ('status', models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], max_length=200, null=True)),
                ('semister', models.CharField(choices=[('semisterI', 'semisterI'), ('semisterII', 'semisterII')], default='semisterI', max_length=200)),
                ('standing_sec', models.IntegerField(blank=True, null=True)),
                ('standing_all', models.IntegerField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Course')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Section')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Teacher')),
            ],
            options={
                'unique_together': {('course', 'student', 'semister')},
            },
        ),
    ]
