# Generated by Django 2.2.12 on 2021-09-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_assesment_student_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='wholestanding_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
