# Generated by Django 2.2.12 on 2021-09-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_transcript_wholestanding_sec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assesment',
            old_name='final',
            new_name='wholeavg',
        ),
        migrations.RenameField(
            model_name='assesment',
            old_name='mid',
            new_name='wholetot',
        ),
    ]
