# Generated by Django 2.2.12 on 2021-09-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_auto_20210920_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesment',
            name='wholeavg',
        ),
        migrations.AddField(
            model_name='assesment',
            name='wholestatus',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], max_length=200, null=True),
        ),
    ]
