# Generated by Django 2.2.12 on 2021-09-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_upcoming'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upcoming',
        ),
    ]
